### ISSUE TITLE
Can't Edit Attributes

### ISSUE THREAD

**Issue by josueraul** [anlinguist/Numu-Know#6]
Good day Mr. Nelson,

I am unable to edit "A Fishing Memory Story." I have tried using both my email accounts. Is this one that, perhaps, you added? I thought you had given me author capabilities of all documents. 

Thank you for your time sir.

**Comment by anlinguist** [comment]
Hello - the email account that added that document was 'jrm.linguist@gmail.com' -  would you like me to change it to another email account?

**Comment by josueraul** [comment]
It's working now. Must be some sort of delay when I logged onto that account.

**Comment by anlinguist** [comment]
You have 3 associated emails: 
-numu.linguist@gmail.com
-josue.manriquez@gmail.com
-jrm.linguist@gmail.com

Would you like me to migrate all documents to 1 particular account?

**Comment by josueraul** [comment]
Yes might as well just migrate all the the numu.linguist email.
